### ISSUE TITLE
关于cordova的codepush请指教

### ISSUE THREAD

**Issue by huangzhenxian** [iflamed/cordova-huawei-push#1]
你好 我在vux 中的issues 看到你有cordova 的微软 codePush 的使用经验 我现在正在使用codepush 但是一直有一个问题 资源更新不了  我不知道你那边是如何解决的  就是在1.9.2版本的codepush中 每次资源更新后 下一次打开总是会版本回滚 下载的时候立刻安装是成功的 可以留一个即时聊天联系方式吗？

**Comment by iflamed** [comment]
@huangzhenxian 版本回滚原因可能是targetBinaryVersion 这个写错了吧。不知道你不是这个写成了`*`了。 我这边现在是没有出现过回滚的问题。

然后建议你code_push 使用自定义server，微软的code_push server 经常更新比较慢，或者链接不是更新不了。推荐使用这个: https://github.com/lisong/code-push-server

**Comment by huangzhenxian** [comment]
我吐血  原来我没有codePush.notifyApplicationReady  。。。。。。。。  那么长的英文文档  我英语差  今天一个词一个词去读 才发现问题了

**Comment by iflamed** [comment]
坚持下来就好了，英语文档很多的。

**Comment by huangzhenxian** [comment]
能加好友一起讨论吗 我现在几个项目都用Cordova开发

**Comment by iflamed** [comment]
可以呀。我邮箱是iflamed@gmail.com，你把你QQ号或者微信号发到我邮箱吧。

发自 刘兵 的 iPhone
