### ISSUE TITLE
推送保活

### ISSUE THREAD

**Issue by liubei1** [iflamed/cordova-huawei-push#2]
这个推送能保活么  再杀掉进程的情况下

**Comment by iflamed** [comment]
@liubei1  华为hms sdk 推送版本，应该兼容性比较好了。我实际测试了一个4.2的系统，关机重启，APP 重启都可以正常搜到推送的。

**Comment by liubei1** [comment]
进程关掉，不重启呢？  像微信，我把进程杀掉，没有启动，还是能收到消息的

**Comment by iflamed** [comment]
也是可以的。你可以了解一下华为HMS 的特性。

**Comment by liubei1** [comment]
好的谢谢
